### ISSUE TITLE
add PDF versions of goog docs, slide decks, etc

### ISSUE THREAD

**Issue by tofr** [hunter-teacher-cert/summer-2020-topics-project-data-mining#4]
...b/c googdoc links are transient, goog is known for changing things w/o warning, docs may accidentally disappear, etc.

a PDF version will help guarantee this repo of greater use to anyone from the cohort who utilizes this repo in the future...

**Comment by tofr** [comment]
...and perhaps export to MS Office format also, for benefit of Tsee, Lisa, others who are requesting it...

**Comment by rdgarber** [comment]
Will do Thanks
